include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  exclude:
    # exclude generated files
    - "**/*.g.dart"

linter:
  rules:
    avoid_renaming_method_parameters: false
    unnecessary_this: false
    use_key_in_widget_constructors: false